/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        'on-secondary-container': '#007165',
        'background': '#f8f9fa',
        'surface-tint': '#4c56af',
        'outline': '#767683',
        'on-secondary-fixed-variant': '#005048',
        'secondary': '#006b5f',
        'primary-fixed': '#e0e0ff',
        'error': '#ba1a1a',
        'on-error': '#ffffff',
        'on-secondary-fixed': '#00201c',
        'on-primary-container': '#8690ee',
        'on-background': '#191c1d',
        'outline-variant': '#c6c5d4',
        'on-tertiary-fixed-variant': '#604100',
        'surface': '#f8f9fa',
        'surface-container-low': '#f3f4f5',
        'on-tertiary-container': '#c98c00',
        'on-secondary': '#ffffff',
        'on-primary-fixed': '#000767',
        'inverse-on-surface': '#f0f1f2',
        'tertiary-fixed-dim': '#ffba38',
        'on-tertiary-fixed': '#281900',
        'error-container': '#ffdad6',
        'on-surface-variant': '#454652',
        'surface-container': '#edeeef',
        'on-tertiary': '#ffffff',
        'inverse-primary': '#bdc2ff',
        'inverse-surface': '#2e3132',
        'surface-container-high': '#e7e8e9',
        'surface-container-highest': '#e1e3e4',
        'secondary-fixed-dim': '#70d8c8',
        'tertiary': '#271800',
        'secondary-fixed': '#8df5e4',
        'tertiary-fixed': '#ffdeac',
        'secondary-container': '#8df5e4',
        'surface-container-lowest': '#ffffff',
        'tertiary-container': '#422c00',
        'surface-bright': '#f8f9fa',
        'on-primary-fixed-variant': '#343d96',
        'on-surface': '#191c1d',
        'primary-fixed-dim': '#bdc2ff',
        'surface-variant': '#e1e3e4',
        'primary': '#000666',
        'surface-dim': '#d9dadb',
        'primary-container': '#1a237e',
        'on-primary': '#ffffff',
        'on-error-container': '#93000a',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      fontFamily: {
        headline: ['Manrope', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        label: ['Inter', 'sans-serif'],
      },
    },
  },
  plugins: [],
};
