"""Static bank of TEF Canada Section A ("fait divers") writing prompts.

Replaces on-demand AI question generation (formerly prompt_question_generation.py).
Each entry's opening line is sourced from published TEF Canada Section A practice
material (see source_url); the numbered Type de document / Objectif / Consignes
framing mirrors the exam's own standard Section A task instructions.
"""

_TEMPLATE = """1. Type de document: le début d'un article de presse (rubrique faits divers)
2. Objectif: écrire la suite de l'article (80 mots minimum)
3. Consignes:
   - Terminez l'article en ajoutant à la suite un texte de 80 mots minimum.
   - Rédigez en plusieurs paragraphes.
   - Ne recopiez pas et ne résumez pas le début de l'article : apportez des informations nouvelles.
4. Début de l'article: {opening}"""

# (title, opening line(s), source_url)
_RAW = [
    ("Fillette coincée dans une pièce",
     "Une petite fille de 4 ans est restée coincée dans une pièce pendant plus de deux heures…",
     "https://frademy.com/liste-sujets-tef"),
    ("Collision d'hélicoptères à Limoges",
     "Deux hélicoptères sont entrés en collision durant un spectacle annuel à Limoges…",
     "https://frademy.com/liste-sujets-tef"),
    ("Téléphone en feu dans un train",
     "Le téléphone d'un passager a subitement pris feu durant son voyage en train…",
     "https://frademy.com/liste-sujets-tef"),
    ("Avalanche sur des alpinistes",
     "Alors qu'un couple d'alpinistes dormait dans une tente à la montagne, une avalanche s'est produite…",
     "https://frademy.com/liste-sujets-tef"),
    ("Tentative de détournement d'avion",
     "Un homme a tenté de détourner un avion pour un motif bien particulier…",
     "https://frademy.com/liste-sujets-tef"),
    ("Tempête de neige au Canada",
     "Les habitants d'un petit village canadien ont été les victimes de la tempête de neige la plus violente du siècle…",
     "https://frademy.com/liste-sujets-tef"),
    ("Enfant vole la voiture de son père",
     "Un enfant de 8 ans a volé la voiture de luxe de son père et a roulé pendant 200 km…",
     "https://frademy.com/liste-sujets-tef"),
    ("Vol de bijouterie raté",
     "Une voleuse a tenté de voler une bijouterie mais son plan ne s'est pas déroulé comme prévu…",
     "https://frademy.com/liste-sujets-tef"),
    ("Fourgon d'argent pris en embuscade",
     "Un fourgon transportant une importante quantité d'argent a été pris en embuscade par des voleurs…",
     "https://frademy.com/liste-sujets-tef"),
    ("Gorille utilise un smartphone",
     "Un gorille entraîné à utiliser un smartphone a dépassé tous les espoirs des scientifiques…",
     "https://frademy.com/liste-sujets-tef"),
    ("Colonie de vacances rencontre un ours",
     "Une colonie de vacances passait l'après-midi dans un parc lorsqu'ils ont fait la rencontre d'un ours…",
     "https://frademy.com/liste-sujets-tef"),
    ("Découverte dans l'estomac d'un patient",
     "Un chirurgien de renommée internationale a fait une découverte incroyable en ouvrant l'estomac d'un patient…",
     "https://frademy.com/liste-sujets-tef"),
    ("Découverte dans un magasin de jeux vidéo",
     "Un enfant passionné de jeux-vidéo a fait une découverte inattendue en se rendant dans son magasin préféré…",
     "https://frademy.com/liste-sujets-tef"),
    ("Passager inattendu dans la voiture",
     "Une jeune cadre s'est retrouvée nez-à-nez avec un passager bien particulier en rentrant dans sa voiture…",
     "https://frademy.com/liste-sujets-tef"),
    ("Mariée en robe qui fait du stop",
     "Des automobilistes ont rencontré sur leur route une femme en robe de mariée qui faisait du stop…",
     "https://frademy.com/liste-sujets-tef"),
    ("Évasion sophistiquée d'une prisonnière",
     "Une prisonnière en Italie a voulu s'échapper grâce à un plan très sophistiqué…",
     "https://frademy.com/liste-sujets-tef"),
    ("Faux contrôleur de train",
     "Un homme vêtu en contrôleur de train vérifiait les billets des passagers d'une façon bien étrange…",
     "https://frademy.com/liste-sujets-tef"),
    ("Recherche d'emploi sur la A6",
     "Jeudi dernier, Alfred un jeune homme de 24 ans, portant un gilet jaune, s'est affiché sur les bords de l'autoroute Paris-Lyon.",
     "https://tefacademie.com/test-evaluation-du-francais/expression-ecrite-v2/faits-divers/"),
    ("Rongeurs sur les rayons",
     "Samedi dernier un grand supermarché de Marseille a été secoué quand une cliente a fait une crise hystérique dans le rayon des fruits et légumes.",
     "https://tefacademie.com/test-evaluation-du-francais/expression-ecrite-v2/faits-divers/"),
    ("100 000 $ trouvés aux États-Unis",
     "Une découverte fabuleuse a été faite hier par Michel Ledoux, un jeune entrepreneur dans l'État de Louisiane aux États-Unis.",
     "https://tefacademie.com/test-evaluation-du-francais/expression-ecrite-v2/faits-divers/"),
    ("Un grand lion en fuite",
     "Les habitants de Montfaucon n'ont pas fermé l'œil la nuit dernière, et pour cause, un lion en cavale terrorise les habitants.",
     "https://tefacademie.com/test-evaluation-du-francais/expression-ecrite-v2/faits-divers/"),
    ("Bébé retrouvé dans une gare",
     "La gare de Vendôme a été le théâtre d'une grande mobilisation au sein des forces de l'ordre suite à la découverte d'un bébé de 18 mois.",
     "https://tefacademie.com/test-evaluation-du-francais/expression-ecrite-v2/faits-divers/"),
    ("Fillette tombée dans la Seine",
     "Une fillette de 11 ans a été sauvée de la noyade ce dimanche 11 mars, vers 10 heures, par un touriste québécois.",
     "https://tefacademie.com/test-evaluation-du-francais/expression-ecrite-v2/faits-divers/"),
    ("Femme perdue à l'aéroport de Beyrouth",
     "La maman avait disparu dans l'aéroport de Beyrouth le 31 mars 2020. Sa famille l'a finalement retrouvée en juin.",
     "https://tefacademie.com/test-evaluation-du-francais/expression-ecrite-v2/faits-divers/"),
    ("Argent trouvé sur la pelouse",
     "Françoise a rapporté aux policiers les billets qu'elle a trouvés sur sa pelouse ce mardi matin.",
     "https://tefacademie.com/test-evaluation-du-francais/expression-ecrite-v2/faits-divers/"),
    ("Ours polaire sur un bateau de croisière",
     "Ce mardi 14 février, un ours polaire a été signalé par des passagers à bord du bateau de croisière Paradize.",
     "https://tefacademie.com/test-evaluation-du-francais/expression-ecrite-v2/faits-divers/"),
    ("Réseau coupé à Barbès",
     "Une déconnexion intégrale du réseau téléphonique et Internet a été signalée par les riverains de Barbès.",
     "https://tefacademie.com/test-evaluation-du-francais/expression-ecrite-v2/faits-divers/"),
    ("Un renard vole un passeport",
     "Les domaines sauvages des Wilkinson au Québec ont été le théâtre d'une scène peu commune mercredi matin.",
     "https://tefacademie.com/test-evaluation-du-francais/expression-ecrite-v2/faits-divers/"),
    ("Fillette perdue au zoo de Montpellier",
     "Une fillette de 8 ans disparaît dans un parc zoologique à Montpellier, a été retrouvée après quelques…",
     "https://tefacademie.com/test-evaluation-du-francais/expression-ecrite-v2/faits-divers/"),
    ("Motards en vacances sur l'A35",
     "Samedi dernier les vacances d'un couple de motards virent au cauchemar sur l'autoroute de Strasbourg.",
     "https://tefacademie.com/test-evaluation-du-francais/expression-ecrite-v2/faits-divers/"),
    ("Demande en mariage à la tour Eiffel",
     "Mardi dernier, une demande en mariage tourne au drame à la tour Eiffel quand un octogénaire décide…",
     "https://tefacademie.com/test-evaluation-du-francais/expression-ecrite-v2/faits-divers/"),
    ("Dauphin sauveteur en Espagne",
     "Le week-end dernier, un fait insolite marque les côtes atlantiques d'Espagne quand une jeune trentenaire…",
     "https://tefacademie.com/test-evaluation-du-francais/expression-ecrite-v2/faits-divers/"),
    ("Nonagénaire star de télé",
     "Les médias d'aujourd'hui s'embrasent suite à la parution d'un nonagénaire sur le plateau du jeu télé culte.",
     "https://tefacademie.com/test-evaluation-du-francais/expression-ecrite-v2/faits-divers/"),
    ("Diamant volé à l'aéroport d'Ottawa",
     "Un gros diamant de 60 carats perdu, une fille de 17 ans interpellée à l'aéroport d'Ottawa.",
     "https://tefacademie.com/test-evaluation-du-francais/expression-ecrite-v2/faits-divers/"),
    ("Carte au trésor trouvée à Nice",
     "On a tendance à être agacé par les crabes qui creusent dans nos plages, pourtant un pêcheur niçois leur doit…",
     "https://tefacademie.com/test-evaluation-du-francais/expression-ecrite-v2/faits-divers/"),
    ("Vacarme inédit dans le 15e arrondissement",
     "Hier soir, le calme qui prévalait habituellement dans le 15e arrondissement a été supplanté par un vacarme inédit.",
     "https://tefacademie.com/test-evaluation-du-francais/expression-ecrite-v2/faits-divers/"),
    ("Patient mystère à Salamanque",
     "L'enceinte sanitaire de Salamanque en Espagne a été ébranlée le week-end dernier par une nouvelle…",
     "https://tefacademie.com/test-evaluation-du-francais/expression-ecrite-v2/faits-divers/"),
    ("Vol de bijouterie en centre-ville",
     "Hier soir, aux alentours de 22 heures, une bijouterie située sur la rue de la Paix a été…",
     "https://prepmyfrench.com/blogs/tef-writing-section-a-fait-divers-samples"),
    ("Chat sauvé de la Seine par un passant",
     "Ce matin, un incident pour le moins inhabituel s'est produit sur les quais de la Seine…",
     "https://prepmyfrench.com/blogs/tef-writing-section-a-fait-divers-samples"),
    ("Carambolage sur l'autoroute A1",
     "Un accident impliquant deux poids lourds a provoqué un embouteillage monstre ce vendredi matin…",
     "https://prepmyfrench.com/blogs/tef-writing-section-a-fait-divers-samples"),
    ("Fourgon blindé accidenté sur le périphérique",
     "Lundi après-midi, l'incident s'est passé sur le périphérique de Paris…",
     "https://lingorelic.com/writing-task-samples-tef-canada-section-a/"),
    ("Voiture de sport sur l'autoroute A6",
     "Thomas Dupont, 25 ans, conduisait une voiture de sport sur l'autoroute A6…",
     "https://lingorelic.com/writing-task-samples-tef-canada-section-a/"),
    ("Chien retrouve un enfant perdu",
     "Samedi après-midi, une famille se promenait dans un grand parc lorsqu'elle a perdu de vue son fils de huit ans. Après plusieurs minutes de recherche, les parents ont remarqué que leur chien avait disparu lui aussi.",
     "https://rossielts.com/tef-canada-tips/tef-canada-expression-ecrite-section-a-fait-divers/"),
    ("Coffre au trésor dans un jardin de banlieue",
     "Une découverte insolite a bouleversé le calme de la banlieue de Lyon mardi dernier…",
     "https://languagenext.com/blog/tef-canada-writing-sample-papers/"),
    ("Erreur de courrier étonnante à Nice",
     "Un habitant de Nice a reçu hier un courrier qui ne lui était manifestement pas destiné. En ouvrant l'enveloppe, il a découvert un document très important…",
     "https://francaisavecpierre.com/exemple-tef/"),
]

QUESTIONS_TASK_A = [
    {
        "id": f"a{idx + 1:02d}",
        "title": title,
        "preview": opening,
        "prompt": _TEMPLATE.format(opening=opening),
        "source_url": source_url,
    }
    for idx, (title, opening, source_url) in enumerate(_RAW)
]
